name: RDP via ngrok

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP user and permissions
        shell: pwsh
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok TCP tunnel
        uses: wernight/ngrok@v3
        with:
          args: tcp 3389
          authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
